### ISSUE TITLE
Update to Prettier v3

### ISSUE THREAD

**Issue by Hirschfuchs** [shellscape/prettier-plugin-package#22]
Add support for Prettier 3: https://prettier.io/blog/2023/07/05/3.0.0.html

**Comment by viceice** [comment]
Why is this closed? There is still no release which is compatible with prettier v3. 😢

**Comment by viceice** [comment]
This is the error we get with prettier v3
```sh
> prettier --ignore-unknown --check "**/*.*"

Checking formatting...
Error:  package.json: TypeError: Cannot read properties of undefined (reading 'filter')
Error:      at sort (/home/runner/work/pep440/pep440/node_modules/.pnpm/prettier-plugin-package@1.3.1_prettier@3.0.0/node_modules/prettier-plugin-package/lib/rules/sort.js:58:23)
Error:      at format (/home/runner/work/pep440/pep440/node_modules/.pnpm/prettier-plugin-package@1.3.1_prettier@3.0.0/node_modules/prettier-plugin-package/lib/index.js:24:15)
Error:      at Object.parse (/home/runner/work/pep440/pep440/node_modules/.pnpm/prettier-plugin-package@1.3.1_prettier@3.0.0/node_modules/prettier-plugin-package/lib/index.js:45:[28](https://github.com/renovatebot/pep440/actions/runs/5756317505/job/15605489229?pr=368#step:7:30))
Error:      at parse (file:///home/runner/work/pep440/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:17080:24)
Error:      at async coreFormat (file:///home/runner/work/pep440/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18401:7)
Error:      at async formatWithCursor (file:///home/runner/work/pep440/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18603:14)
Error:      at async formatFiles (file:///home/runner/work/pep440/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/internal/cli.mjs:6778:18)
Error:      at async main (file:///home/runner/work/pep440/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/internal/cli.mjs:6970:5)
Error:      at async Module.run (file:///home/runner/work/pep4[40](https://github.com/renovatebot/pep440/actions/runs/5756317505/job/15605489229?pr=368#step:7:42)/pep440/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/internal/cli.mjs:6924:5)
All matched files use Prettier code style!
```

**Comment by viceice** [comment]
props is undefined here:
https://github.com/shellscape/prettier-plugin-package/blob/bfc46e6e4278bf3c55b46fe4d40abdf2096022c5/lib/rules/sort.js#L58-L58
https://github.com/shellscape/prettier-plugin-package/blob/bfc46e6e4278bf3c55b46fe4d40abdf2096022c5/lib/index.js#L24

probably because of ast changes here
https://github.com/shellscape/prettier-plugin-package/blob/bfc46e6e4278bf3c55b46fe4d40abdf2096022c5/lib/index.js#L44-L45

**Comment by acidoxee** [comment]
@shellscape it seems @viceice has prepared a PR to fix this 🎉 do you think you could take a look? I'm currently holding off from updating Prettier to v3 because of your super useful plugin 😉
